DROP TABLE IF EXISTS AdminRoomRequestManagement;
DROP TABLE IF EXISTS RoommateRequest;
DROP TABLE IF EXISTS MaintenanceRequest;
DROP TABLE IF EXISTS RoomRequest;
drop table if exists session;
drop table if exists Notifications;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS Room;