DROP TABLE IF EXISTS AdminRoomRequestManagement;
DROP TABLE IF EXISTS RoommateRequest;
DROP TABLE IF EXISTS MaintenanceRequest;
DROP TABLE IF EXISTS RoomRequest;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Admin;